// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(libveritas_uniffiFFI)
import libveritas_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_libveritas_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_libveritas_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureLibveritasUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol AnchorsProtocol: AnyObject, Sendable {
    
}
open class Anchors: AnchorsProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_anchors(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_anchors(pointer, $0) }
    }

    
public static func fromJson(json: String)throws  -> Anchors  {
    return try  FfiConverterTypeAnchors_lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_constructor_anchors_from_json(
        FfiConverterString.lower(json),$0
    )
})
}
    

    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnchors: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Anchors

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Anchors {
        return Anchors(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Anchors) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Anchors {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Anchors, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnchors_lift(_ pointer: UnsafeMutableRawPointer) throws -> Anchors {
    return try FfiConverterTypeAnchors.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnchors_lower(_ value: Anchors) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAnchors.lower(value)
}






public protocol MessageProtocol: AnyObject, Sendable {
    
    /**
     * Serialize the message to borsh bytes.
     */
    func toBytes()  -> Data
    
    /**
     * Update offchain data and/or root certificates on this message.
     *
     * - `name`: handle string (e.g. "alice@bitcoin", "@bitcoin", "#12-12")
     * - `offchain_data`: borsh-encoded OffchainData (optional)
     * - `delegate_offchain_data`: borsh-encoded OffchainData (optional)
     * - `cert`: borsh-encoded Certificate (optional, root only — for receipt refresh)
     */
    func update(updates: [DataUpdateEntry]) throws 
    
}
open class Message: MessageProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_message(self.pointer, $0) }
    }
    /**
     * Decode a message from borsh bytes.
     */
public convenience init(bytes: Data)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_constructor_message_new(
        FfiConverterData.lower(bytes),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_message(pointer, $0) }
    }

    

    
    /**
     * Serialize the message to borsh bytes.
     */
open func toBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_message_to_bytes(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Update offchain data and/or root certificates on this message.
     *
     * - `name`: handle string (e.g. "alice@bitcoin", "@bitcoin", "#12-12")
     * - `offchain_data`: borsh-encoded OffchainData (optional)
     * - `delegate_offchain_data`: borsh-encoded OffchainData (optional)
     * - `cert`: borsh-encoded Certificate (optional, root only — for receipt refresh)
     */
open func update(updates: [DataUpdateEntry])throws   {try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_message_update(self.uniffiClonePointer(),
        FfiConverterSequenceTypeDataUpdateEntry.lower(updates),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Message

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Message {
        return Message(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Message) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Message {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Message, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lift(_ pointer: UnsafeMutableRawPointer) throws -> Message {
    return try FfiConverterTypeMessage.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lower(_ value: Message) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMessage.lower(value)
}






/**
 * Builder for constructing messages from update requests and chain proofs.
 */
public protocol MessageBuilderProtocol: AnyObject, Sendable {
    
    /**
     * Build the message from a borsh-encoded ChainProof.
     *
     * Consumes the builder — cannot be called twice.
     */
    func build(chainProof: Data) throws  -> Message
    
    /**
     * Returns the chain proof request as JSON.
     *
     * Send this to the provider/fabric to get the chain proofs needed for `build()`.
     */
    func chainProofRequest() throws  -> String
    
}
/**
 * Builder for constructing messages from update requests and chain proofs.
 */
open class MessageBuilder: MessageBuilderProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_messagebuilder(self.pointer, $0) }
    }
    /**
     * Create a builder from a list of update entries.
     */
public convenience init(requests: [UpdateEntry])throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_constructor_messagebuilder_new(
        FfiConverterSequenceTypeUpdateEntry.lower(requests),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_messagebuilder(pointer, $0) }
    }

    

    
    /**
     * Build the message from a borsh-encoded ChainProof.
     *
     * Consumes the builder — cannot be called twice.
     */
open func build(chainProof: Data)throws  -> Message  {
    return try  FfiConverterTypeMessage_lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_messagebuilder_build(self.uniffiClonePointer(),
        FfiConverterData.lower(chainProof),$0
    )
})
}
    
    /**
     * Returns the chain proof request as JSON.
     *
     * Send this to the provider/fabric to get the chain proofs needed for `build()`.
     */
open func chainProofRequest()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_messagebuilder_chain_proof_request(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageBuilder: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MessageBuilder

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MessageBuilder {
        return MessageBuilder(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MessageBuilder) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageBuilder {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MessageBuilder, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageBuilder_lift(_ pointer: UnsafeMutableRawPointer) throws -> MessageBuilder {
    return try FfiConverterTypeMessageBuilder.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageBuilder_lower(_ value: MessageBuilder) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMessageBuilder.lower(value)
}






public protocol QueryContextProtocol: AnyObject, Sendable {
    
    /**
     * Add a handle to verify (e.g. "alice@bitcoin").
     * If no requests are added, all handles in the message are verified.
     */
    func addRequest(handle: String) throws 
    
    /**
     * Add a known zone from stored bytes (from a previous verification).
     */
    func addZone(zoneBytes: Data) throws 
    
}
open class QueryContext: QueryContextProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_querycontext(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_libveritas_uniffi_fn_constructor_querycontext_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_querycontext(pointer, $0) }
    }

    

    
    /**
     * Add a handle to verify (e.g. "alice@bitcoin").
     * If no requests are added, all handles in the message are verified.
     */
open func addRequest(handle: String)throws   {try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_querycontext_add_request(self.uniffiClonePointer(),
        FfiConverterString.lower(handle),$0
    )
}
}
    
    /**
     * Add a known zone from stored bytes (from a previous verification).
     */
open func addZone(zoneBytes: Data)throws   {try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_querycontext_add_zone(self.uniffiClonePointer(),
        FfiConverterData.lower(zoneBytes),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQueryContext: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = QueryContext

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> QueryContext {
        return QueryContext(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: QueryContext) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QueryContext {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: QueryContext, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueryContext_lift(_ pointer: UnsafeMutableRawPointer) throws -> QueryContext {
    return try FfiConverterTypeQueryContext.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueryContext_lower(_ value: QueryContext) -> UnsafeMutableRawPointer {
    return FfiConverterTypeQueryContext.lower(value)
}






/**
 * Serialized records ready to be signed.
 */
public protocol RecordSetProtocol: AnyObject, Sendable {
    
    /**
     * The 32-byte hash to sign.
     */
    func id()  -> Data
    
}
/**
 * Serialized records ready to be signed.
 */
open class RecordSet: RecordSetProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_recordset(self.pointer, $0) }
    }
    /**
     * Create a record set from a sequence number and a JSON string of key-value pairs.
     *
     * Records are sorted by key for deterministic serialization.
     * Example: `'{"nostr":"npub1...","ipv4":"127.0.0.1"}'`
     */
public convenience init(seq: UInt32, recordsJson: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_constructor_recordset_new(
        FfiConverterUInt32.lower(seq),
        FfiConverterString.lower(recordsJson),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_recordset(pointer, $0) }
    }

    

    
    /**
     * The 32-byte hash to sign.
     */
open func id() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_recordset_id(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecordSet: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = RecordSet

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> RecordSet {
        return RecordSet(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: RecordSet) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecordSet {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: RecordSet, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordSet_lift(_ pointer: UnsafeMutableRawPointer) throws -> RecordSet {
    return try FfiConverterTypeRecordSet.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordSet_lower(_ value: RecordSet) -> UnsafeMutableRawPointer {
    return FfiConverterTypeRecordSet.lower(value)
}






public protocol VerifiedMessageProtocol: AnyObject, Sendable {
    
    func certificate(handle: String) throws  -> Certificate?
    
    func certificates()  -> [Certificate]
    
    /**
     * Get the verified message for rebroadcasting or updating.
     */
    func message()  -> Message
    
    /**
     * Get the verified message as borsh bytes.
     */
    func messageBytes()  -> Data
    
    func zones()  -> [Zone]
    
}
open class VerifiedMessage: VerifiedMessageProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_verifiedmessage(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_verifiedmessage(pointer, $0) }
    }

    

    
open func certificate(handle: String)throws  -> Certificate?  {
    return try  FfiConverterOptionTypeCertificate.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_verifiedmessage_certificate(self.uniffiClonePointer(),
        FfiConverterString.lower(handle),$0
    )
})
}
    
open func certificates() -> [Certificate]  {
    return try!  FfiConverterSequenceTypeCertificate.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_verifiedmessage_certificates(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the verified message for rebroadcasting or updating.
     */
open func message() -> Message  {
    return try!  FfiConverterTypeMessage_lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_verifiedmessage_message(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the verified message as borsh bytes.
     */
open func messageBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_verifiedmessage_message_bytes(self.uniffiClonePointer(),$0
    )
})
}
    
open func zones() -> [Zone]  {
    return try!  FfiConverterSequenceTypeZone.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_verifiedmessage_zones(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerifiedMessage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = VerifiedMessage

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> VerifiedMessage {
        return VerifiedMessage(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: VerifiedMessage) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerifiedMessage {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: VerifiedMessage, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedMessage_lift(_ pointer: UnsafeMutableRawPointer) throws -> VerifiedMessage {
    return try FfiConverterTypeVerifiedMessage.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedMessage_lower(_ value: VerifiedMessage) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVerifiedMessage.lower(value)
}






public protocol VeritasProtocol: AnyObject, Sendable {
    
    func isFinalized(commitmentHeight: UInt32)  -> Bool
    
    func newestAnchor()  -> UInt32
    
    func oldestAnchor()  -> UInt32
    
    func sovereigntyFor(commitmentHeight: UInt32)  -> String
    
    /**
     * Verify a message against a query context.
     */
    func verifyMessage(ctx: QueryContext, msg: Message) throws  -> VerifiedMessage
    
}
open class Veritas: VeritasProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_veritas(self.pointer, $0) }
    }
public convenience init(anchors: Anchors)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_constructor_veritas_new(
        FfiConverterTypeAnchors_lower(anchors),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_veritas(pointer, $0) }
    }

    
public static func withDevMode(anchors: Anchors)throws  -> Veritas  {
    return try  FfiConverterTypeVeritas_lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_constructor_veritas_with_dev_mode(
        FfiConverterTypeAnchors_lower(anchors),$0
    )
})
}
    

    
open func isFinalized(commitmentHeight: UInt32) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_veritas_is_finalized(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(commitmentHeight),$0
    )
})
}
    
open func newestAnchor() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_veritas_newest_anchor(self.uniffiClonePointer(),$0
    )
})
}
    
open func oldestAnchor() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_veritas_oldest_anchor(self.uniffiClonePointer(),$0
    )
})
}
    
open func sovereigntyFor(commitmentHeight: UInt32) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_veritas_sovereignty_for(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(commitmentHeight),$0
    )
})
}
    
    /**
     * Verify a message against a query context.
     */
open func verifyMessage(ctx: QueryContext, msg: Message)throws  -> VerifiedMessage  {
    return try  FfiConverterTypeVerifiedMessage_lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_veritas_verify_message(self.uniffiClonePointer(),
        FfiConverterTypeQueryContext_lower(ctx),
        FfiConverterTypeMessage_lower(msg),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVeritas: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Veritas

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Veritas {
        return Veritas(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Veritas) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Veritas {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Veritas, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVeritas_lift(_ pointer: UnsafeMutableRawPointer) throws -> Veritas {
    return try FfiConverterTypeVeritas.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVeritas_lower(_ value: Veritas) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVeritas.lower(value)
}






public protocol ZoneProtocol: AnyObject, Sendable {
    
    func anchor()  -> UInt32
    
    func commitment()  -> CommitmentState
    
    func data()  -> Data?
    
    func delegate()  -> DelegateState
    
    func handle()  -> String
    
    func isBetterThan(other: Zone) throws  -> Bool
    
    func offchainData()  -> OffchainRecord?
    
    func scriptPubkey()  -> Data
    
    func sovereignty()  -> String
    
    func toBytes()  -> Data
    
    func toJson() throws  -> String
    
}
open class Zone: ZoneProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_libveritas_uniffi_fn_clone_zone(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_libveritas_uniffi_fn_free_zone(pointer, $0) }
    }

    

    
open func anchor() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_anchor(self.uniffiClonePointer(),$0
    )
})
}
    
open func commitment() -> CommitmentState  {
    return try!  FfiConverterTypeCommitmentState_lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_commitment(self.uniffiClonePointer(),$0
    )
})
}
    
open func data() -> Data?  {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_data(self.uniffiClonePointer(),$0
    )
})
}
    
open func delegate() -> DelegateState  {
    return try!  FfiConverterTypeDelegateState_lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_delegate(self.uniffiClonePointer(),$0
    )
})
}
    
open func handle() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_handle(self.uniffiClonePointer(),$0
    )
})
}
    
open func isBetterThan(other: Zone)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_zone_is_better_than(self.uniffiClonePointer(),
        FfiConverterTypeZone_lower(other),$0
    )
})
}
    
open func offchainData() -> OffchainRecord?  {
    return try!  FfiConverterOptionTypeOffchainRecord.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_offchain_data(self.uniffiClonePointer(),$0
    )
})
}
    
open func scriptPubkey() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_script_pubkey(self.uniffiClonePointer(),$0
    )
})
}
    
open func sovereignty() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_sovereignty(self.uniffiClonePointer(),$0
    )
})
}
    
open func toBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_method_zone_to_bytes(self.uniffiClonePointer(),$0
    )
})
}
    
open func toJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_method_zone_to_json(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZone: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Zone

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Zone {
        return Zone(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Zone) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Zone {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Zone, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZone_lift(_ pointer: UnsafeMutableRawPointer) throws -> Zone {
    return try FfiConverterTypeZone.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZone_lower(_ value: Zone) -> UnsafeMutableRawPointer {
    return FfiConverterTypeZone.lower(value)
}




public struct Certificate {
    public var subject: String
    public var certType: String
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(subject: String, certType: String, bytes: Data) {
        self.subject = subject
        self.certType = certType
        self.bytes = bytes
    }
}

#if compiler(>=6)
extension Certificate: Sendable {}
#endif


extension Certificate: Equatable, Hashable {
    public static func ==(lhs: Certificate, rhs: Certificate) -> Bool {
        if lhs.subject != rhs.subject {
            return false
        }
        if lhs.certType != rhs.certType {
            return false
        }
        if lhs.bytes != rhs.bytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(subject)
        hasher.combine(certType)
        hasher.combine(bytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCertificate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Certificate {
        return
            try Certificate(
                subject: FfiConverterString.read(from: &buf), 
                certType: FfiConverterString.read(from: &buf), 
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Certificate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.subject, into: &buf)
        FfiConverterString.write(value.certType, into: &buf)
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCertificate_lift(_ buf: RustBuffer) throws -> Certificate {
    return try FfiConverterTypeCertificate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCertificate_lower(_ value: Certificate) -> RustBuffer {
    return FfiConverterTypeCertificate.lower(value)
}


/**
 * Data update entry for Message.update() — no cert field.
 */
public struct DataUpdateEntry {
    public var name: String
    public var offchainData: Data?
    public var delegateOffchainData: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, offchainData: Data?, delegateOffchainData: Data?) {
        self.name = name
        self.offchainData = offchainData
        self.delegateOffchainData = delegateOffchainData
    }
}

#if compiler(>=6)
extension DataUpdateEntry: Sendable {}
#endif


extension DataUpdateEntry: Equatable, Hashable {
    public static func ==(lhs: DataUpdateEntry, rhs: DataUpdateEntry) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.offchainData != rhs.offchainData {
            return false
        }
        if lhs.delegateOffchainData != rhs.delegateOffchainData {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(offchainData)
        hasher.combine(delegateOffchainData)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataUpdateEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataUpdateEntry {
        return
            try DataUpdateEntry(
                name: FfiConverterString.read(from: &buf), 
                offchainData: FfiConverterOptionData.read(from: &buf), 
                delegateOffchainData: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: DataUpdateEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionData.write(value.offchainData, into: &buf)
        FfiConverterOptionData.write(value.delegateOffchainData, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataUpdateEntry_lift(_ buf: RustBuffer) throws -> DataUpdateEntry {
    return try FfiConverterTypeDataUpdateEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataUpdateEntry_lower(_ value: DataUpdateEntry) -> RustBuffer {
    return FfiConverterTypeDataUpdateEntry.lower(value)
}


public struct OffchainRecord {
    public var seq: UInt32
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(seq: UInt32, data: Data) {
        self.seq = seq
        self.data = data
    }
}

#if compiler(>=6)
extension OffchainRecord: Sendable {}
#endif


extension OffchainRecord: Equatable, Hashable {
    public static func ==(lhs: OffchainRecord, rhs: OffchainRecord) -> Bool {
        if lhs.seq != rhs.seq {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(seq)
        hasher.combine(data)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOffchainRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OffchainRecord {
        return
            try OffchainRecord(
                seq: FfiConverterUInt32.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: OffchainRecord, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.seq, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOffchainRecord_lift(_ buf: RustBuffer) throws -> OffchainRecord {
    return try FfiConverterTypeOffchainRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOffchainRecord_lower(_ value: OffchainRecord) -> RustBuffer {
    return FfiConverterTypeOffchainRecord.lower(value)
}


/**
 * Update entry for MessageBuilder — includes optional cert.
 */
public struct UpdateEntry {
    public var name: String
    public var offchainData: Data?
    public var delegateOffchainData: Data?
    public var cert: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, offchainData: Data?, delegateOffchainData: Data?, cert: Data?) {
        self.name = name
        self.offchainData = offchainData
        self.delegateOffchainData = delegateOffchainData
        self.cert = cert
    }
}

#if compiler(>=6)
extension UpdateEntry: Sendable {}
#endif


extension UpdateEntry: Equatable, Hashable {
    public static func ==(lhs: UpdateEntry, rhs: UpdateEntry) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.offchainData != rhs.offchainData {
            return false
        }
        if lhs.delegateOffchainData != rhs.delegateOffchainData {
            return false
        }
        if lhs.cert != rhs.cert {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(offchainData)
        hasher.combine(delegateOffchainData)
        hasher.combine(cert)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUpdateEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UpdateEntry {
        return
            try UpdateEntry(
                name: FfiConverterString.read(from: &buf), 
                offchainData: FfiConverterOptionData.read(from: &buf), 
                delegateOffchainData: FfiConverterOptionData.read(from: &buf), 
                cert: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: UpdateEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionData.write(value.offchainData, into: &buf)
        FfiConverterOptionData.write(value.delegateOffchainData, into: &buf)
        FfiConverterOptionData.write(value.cert, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUpdateEntry_lift(_ buf: RustBuffer) throws -> UpdateEntry {
    return try FfiConverterTypeUpdateEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUpdateEntry_lower(_ value: UpdateEntry) -> RustBuffer {
    return FfiConverterTypeUpdateEntry.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CommitmentState {
    
    case exists(stateRoot: Data, prevRoot: Data?, rollingHash: Data, blockHeight: UInt32, receiptHash: Data?
    )
    case empty
    case unknown
}


#if compiler(>=6)
extension CommitmentState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCommitmentState: FfiConverterRustBuffer {
    typealias SwiftType = CommitmentState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CommitmentState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .exists(stateRoot: try FfiConverterData.read(from: &buf), prevRoot: try FfiConverterOptionData.read(from: &buf), rollingHash: try FfiConverterData.read(from: &buf), blockHeight: try FfiConverterUInt32.read(from: &buf), receiptHash: try FfiConverterOptionData.read(from: &buf)
        )
        
        case 2: return .empty
        
        case 3: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CommitmentState, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .exists(stateRoot,prevRoot,rollingHash,blockHeight,receiptHash):
            writeInt(&buf, Int32(1))
            FfiConverterData.write(stateRoot, into: &buf)
            FfiConverterOptionData.write(prevRoot, into: &buf)
            FfiConverterData.write(rollingHash, into: &buf)
            FfiConverterUInt32.write(blockHeight, into: &buf)
            FfiConverterOptionData.write(receiptHash, into: &buf)
            
        
        case .empty:
            writeInt(&buf, Int32(2))
        
        
        case .unknown:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommitmentState_lift(_ buf: RustBuffer) throws -> CommitmentState {
    return try FfiConverterTypeCommitmentState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommitmentState_lower(_ value: CommitmentState) -> RustBuffer {
    return FfiConverterTypeCommitmentState.lower(value)
}


extension CommitmentState: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DelegateState {
    
    case exists(scriptPubkey: Data, data: Data?, offchainData: OffchainRecord?
    )
    case empty
    case unknown
}


#if compiler(>=6)
extension DelegateState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDelegateState: FfiConverterRustBuffer {
    typealias SwiftType = DelegateState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DelegateState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .exists(scriptPubkey: try FfiConverterData.read(from: &buf), data: try FfiConverterOptionData.read(from: &buf), offchainData: try FfiConverterOptionTypeOffchainRecord.read(from: &buf)
        )
        
        case 2: return .empty
        
        case 3: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DelegateState, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .exists(scriptPubkey,data,offchainData):
            writeInt(&buf, Int32(1))
            FfiConverterData.write(scriptPubkey, into: &buf)
            FfiConverterOptionData.write(data, into: &buf)
            FfiConverterOptionTypeOffchainRecord.write(offchainData, into: &buf)
            
        
        case .empty:
            writeInt(&buf, Int32(2))
        
        
        case .unknown:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDelegateState_lift(_ buf: RustBuffer) throws -> DelegateState {
    return try FfiConverterTypeDelegateState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDelegateState_lower(_ value: DelegateState) -> RustBuffer {
    return FfiConverterTypeDelegateState.lower(value)
}


extension DelegateState: Equatable, Hashable {}







public enum VeritasError: Swift.Error {

    
    
    case InvalidInput(message: String
    )
    case VerificationFailed(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVeritasError: FfiConverterRustBuffer {
    typealias SwiftType = VeritasError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VeritasError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .VerificationFailed(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VeritasError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidInput(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .VerificationFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVeritasError_lift(_ buf: RustBuffer) throws -> VeritasError {
    return try FfiConverterTypeVeritasError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVeritasError_lower(_ value: VeritasError) -> RustBuffer {
    return FfiConverterTypeVeritasError.lower(value)
}


extension VeritasError: Equatable, Hashable {}




extension VeritasError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCertificate: FfiConverterRustBuffer {
    typealias SwiftType = Certificate?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCertificate.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCertificate.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeOffchainRecord: FfiConverterRustBuffer {
    typealias SwiftType = OffchainRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeOffchainRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeOffchainRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeZone: FfiConverterRustBuffer {
    typealias SwiftType = [Zone]

    public static func write(_ value: [Zone], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeZone.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Zone] {
        let len: Int32 = try readInt(&buf)
        var seq = [Zone]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeZone.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCertificate: FfiConverterRustBuffer {
    typealias SwiftType = [Certificate]

    public static func write(_ value: [Certificate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCertificate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Certificate] {
        let len: Int32 = try readInt(&buf)
        var seq = [Certificate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCertificate.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDataUpdateEntry: FfiConverterRustBuffer {
    typealias SwiftType = [DataUpdateEntry]

    public static func write(_ value: [DataUpdateEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDataUpdateEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DataUpdateEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [DataUpdateEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDataUpdateEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUpdateEntry: FfiConverterRustBuffer {
    typealias SwiftType = [UpdateEntry]

    public static func write(_ value: [UpdateEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUpdateEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UpdateEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [UpdateEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUpdateEntry.read(from: &buf))
        }
        return seq
    }
}
/**
 * Create borsh-encoded OffchainData from a RecordSet and a 64-byte Schnorr signature.
 */
public func createOffchainData(recordSet: RecordSet, signature: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_func_create_offchain_data(
        FfiConverterTypeRecordSet_lower(recordSet),
        FfiConverterData.lower(signature),$0
    )
})
}
/**
 * Decode stored certificate bytes to JSON.
 */
public func decodeCertificate(bytes: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_func_decode_certificate(
        FfiConverterData.lower(bytes),$0
    )
})
}
/**
 * Decode stored zone bytes to JSON.
 */
public func decodeZone(bytes: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_func_decode_zone(
        FfiConverterData.lower(bytes),$0
    )
})
}
/**
 * Hash a message with the Spaces signed-message prefix (SHA256).
 * Returns the 32-byte digest suitable for Schnorr signing/verification.
 */
public func hashSignableMessage(msg: Data) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_libveritas_uniffi_fn_func_hash_signable_message(
        FfiConverterData.lower(msg),$0
    )
})
}
/**
 * Verify a raw Schnorr signature (no prefix, caller provides the 32-byte message hash).
 *
 * - `msg_hash`: 32-byte SHA256 hash
 * - `signature`: 64-byte Schnorr signature
 * - `pubkey`: 32-byte x-only public key
 */
public func verifySchnorr(msgHash: Data, signature: Data, pubkey: Data)throws   {try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_func_verify_schnorr(
        FfiConverterData.lower(msgHash),
        FfiConverterData.lower(signature),
        FfiConverterData.lower(pubkey),$0
    )
}
}
/**
 * Verify a Schnorr signature over a message using the Spaces signed-message prefix.
 *
 * - `msg`: raw message bytes (prefixed and hashed internally)
 * - `signature`: 64-byte Schnorr signature
 * - `pubkey`: 32-byte x-only public key
 */
public func verifySpacesMessage(msg: Data, signature: Data, pubkey: Data)throws   {try rustCallWithError(FfiConverterTypeVeritasError_lift) {
    uniffi_libveritas_uniffi_fn_func_verify_spaces_message(
        FfiConverterData.lower(msg),
        FfiConverterData.lower(signature),
        FfiConverterData.lower(pubkey),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_libveritas_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_func_create_offchain_data() != 28866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_func_decode_certificate() != 45631) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_func_decode_zone() != 59384) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_func_hash_signable_message() != 19660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_func_verify_schnorr() != 32215) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_func_verify_spaces_message() != 40969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_message_to_bytes() != 48939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_message_update() != 45160) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_messagebuilder_build() != 53738) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_messagebuilder_chain_proof_request() != 17065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_querycontext_add_request() != 60666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_querycontext_add_zone() != 53280) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_recordset_id() != 62743) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_verifiedmessage_certificate() != 39006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_verifiedmessage_certificates() != 2792) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_verifiedmessage_message() != 38387) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_verifiedmessage_message_bytes() != 5718) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_verifiedmessage_zones() != 51808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_veritas_is_finalized() != 15029) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_veritas_newest_anchor() != 205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_veritas_oldest_anchor() != 57268) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_veritas_sovereignty_for() != 5317) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_veritas_verify_message() != 13203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_anchor() != 50943) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_commitment() != 3594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_data() != 65114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_delegate() != 56633) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_handle() != 37290) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_is_better_than() != 46722) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_offchain_data() != 34636) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_script_pubkey() != 64238) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_sovereignty() != 7046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_to_bytes() != 42046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_method_zone_to_json() != 38582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_anchors_from_json() != 36150) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_message_new() != 52348) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_messagebuilder_new() != 13656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_querycontext_new() != 17395) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_recordset_new() != 26032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_veritas_new() != 7569) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_libveritas_uniffi_checksum_constructor_veritas_with_dev_mode() != 2007) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureLibveritasUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all